#!/bin/sh

devmode=0
while getopts "d" OPT; do
    case "$OPT" in 
        d) devmode=1;;
    esac
done

[ "$devmode" = 1 ] && {
    esbuildOpts=--sourcemap
}

#esbuild/typescript stuff
esbuild $(find . -regex '.*\.ts$') --minify --outdir=webservice/www $esbuildOpts

#compile html into one BIG html to avoid having to have all of this in one massive file while working on it. It gets really annoying lol
idx="./webservice/www/new-ui/index.html"
#copy the initial template file to the final output
cp "./webservice/www/new-ui/index-template.html" "$idx"
#for each template
for file in ./webservice/www/new-ui/html-templates/*.html; do
    name="${file##*/}"
    name="${name%.html}"
    #create a template html tag and put it into the final output html file
    cat <<EOTEMPLATE >> "$idx"
<template id="${name}">
$(cat "$file")
</template>

EOTEMPLATE
done

#main go program
${GO:-go} build .
