#!/bin/sh

devmode=0
while getopts "d" OPT; do
    case "$OPT" in 
        d) devmode=1;;
    esac
done

[ "$devmode" = 1 ] && {
    esbuildOpts=--sourcemap
}

esbuild $(find . -regex '.*\.ts$') --minify --outdir=webservice/www $esbuildOpts
${GO:-go} build .
